config/routes.rb
Metus::Engine.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    Metus::PagesController::PAGES.each do |page|
      get "/pages/#{page}", controller: :pages, action: Metus::PagesController.path_to_actionname(page), as: page
    end

    namespace :backend do
      get :welcome, to: 'welcome#show'
      resources :admins, except: :show
    end
  end
end

app/models/metus/application_record.rb
module Metus
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/metus/application_controller.rb
module Metus
  class ApplicationController < ActionController::Base
    def default_url_options
      { locale: I18n.locale }
    end
  end
end

app/controllers/metus/backend/admins_controller.rb
module Metus
  module Backend
    class AdminsController < BackendController
      def index
        @admins = Admin.all
      end

      def new
        @admin = Admin.new
      end

      def create
        password = SecureRandom.hex

        if Admin.create(admin_params.merge(password: password))
          redirect_to backend_admins_path
        else
          render :new, status: :unprocessable_entity
        end
      end

      def edit
        @admin = Admin.find(params[:id])
      end

      def update
        @admin = Admin.find(params[:id])

        if @admin.update(admin_params)
          redirect_to backend_admins_path
        else
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        @admin = Admin.find(params[:id])
        @admin.destroy!

        redirect_to backend_admins_path
      end

      private

      def admin_params
        params.require(:admin).permit(:email)
      end
    end
  end
end

app/controllers/metus/backend/welcome_controller.rb
module Metus
  module Backend
    class WelcomeController < BackendController
      def show
      end
    end
  end
end

app/controllers/metus/backend_controller.rb
module Metus
  class BackendController < ApplicationController
    before_action :authenticate_admin!
  end
end

app/controllers/metus/pages_controller.rb
# frozen_string_literal: true

require 'asciidoctor'
require 'asciidoctor-bibtex'
require 'front_matter_parser'

module Metus
  class PagesController < Metus.public_controller_class
    def self.filename_to_pagename(directory, name)
      [directory, name].select(&:present?).join('/').to_sym
    end

    def self.parse_page(filename)
      directory = File.dirname(filename)
      directory.gsub!(/#{PAGES_DIRECTORY}[\/]?/, '')

      name, extension = basename(File.basename(filename))
      pagename = filename_to_pagename(directory, name)

      {
        name: name,
        extension: extension,
        template: template(pagename, extension),
        directory: directory,
        pagename: pagename,
        actionname: path_to_actionname(pagename),
        filename: filename
      }
    end

    def self.basename(filename)
      [
        split_extension(filename, '.html.haml'),
        split_extension(filename, '.adoc')
      ].compact.first
    end

    def self.split_extension(filename, extension)
      name = File.basename(filename, extension)

      if "#{name}#{extension}" == filename
        return [name, extension]
      end
    end

    def self.path_to_actionname(path)
      path.to_s.gsub('/', '__slash__')
    end

    def self.template(name, extension)
      case extension
      when '.html.haml'
        "pages/#{name}"
      when '.adoc'
        'metus/pages/asciidoc'
      end
    end

    PAGES_DIRECTORY = Rails.root.join('app/views/pages')

    PAGES_WITH_TEMPLATES = Dir[PAGES_DIRECTORY.join('**/*')]
      .reject { |filename| File.directory?(filename) }
      .map { |filename| Metus::PagesController.parse_page(filename) }

    PAGES = PAGES_WITH_TEMPLATES
      .map { |page| page[:pagename] }
      .map(&:to_sym)

    PAGES_WITH_TEMPLATES.each do |page|
      define_method(page[:actionname]) do
        @page = page
        render page[:template]
      end
    end
  end
end

app/controllers/metus/public_controller.rb
module Metus
  class PublicController < ::ApplicationController
  end
end

app/helpers/metus/application_helper.rb
module Metus
  module ApplicationHelper
    include ::Webpacker::Helper

    def current_webpacker_instance
      Metus.webpacker
    end
  end
end

module ApplicationHelper
  def external_link_to(title, path, options = {})
    link_to title, path, options.merge(target: '_blank', rel: 'noopener noreferrer')
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def nav_link_to(title, path, strategy, options = {})
    service = Metus::NavigationService.new(path, strategy, main_app, request, params, options)

    link_to title, path, service.link_options
  end
end

app/views/layouts/metus/application.html.haml
!!!
%html
  %head
    %title
      - if content_for? :page_title
        = content_for :page_title
      - else
        Metus
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "metus/application", media: "all"
    = stylesheet_pack_tag "application", media: "all"
    = javascript_pack_tag "application"
  %body.flex
    .h-full(style="min-width: 10rem")
      - if current_admin.present?
        = render partial: 'navigation'
      - else
        = link_to 'Sign in', new_session_path(Admin.new)

    .bg-gray-100.flex-grow.p-8(style="flex: 1 0 auto")
      = yield

app/views/metus/application/_navigation.html.haml
%nav.h-full.bg-secondary
  %ul
    %li= nav_link_to 'Home', backend_welcome_path, :exact
    %li.title System
    %li= nav_link_to 'Users', backend_admins_path, :controller
    %li= link_to 'Logout', destroy_session_path(current_admin), method: :delete

app/views/metus/backend/admins/_form.html.haml
= simple_form_for [:backend, @admin] do |f|
  = f.input :email, autofocus: true
  = f.submit
  = link_to t('forms.cancel'), backend_admins_path, class: 'button secondary'

app/views/metus/backend/admins/edit.html.haml
%h1 Edit user #{@admin.email}

= render partial: 'form'

app/views/metus/backend/admins/index.html.haml
%h1 Users

.my-4.text-right
  = link_to 'New user', new_backend_admin_path, class: 'button'

- @admins.each do |admin|
  .box.flex.justify-between
    = admin.email
    %div
      = link_to 'Edit', edit_backend_admin_path(admin), class: 'button secondary small'
      = link_to 'Delete', backend_admin_path(admin), method: :delete, class: 'button secondary small'

app/views/metus/backend/admins/new.html.haml
%h1 New user

= render partial: 'form'

app/views/metus/backend/welcome/show.html.haml
%h1 Welcome, #{current_admin.email}

.mt-8.grid.grid-cols-1.lg:grid-cols-3
  .box.text-center
    .text-6xl.font-bold= Admin.count
    users

app/views/metus/pages/asciidoc.html.haml
= content_for :page_title do
  = FrontMatterParser::Parser.new(:md).call(File.read(@page[:filename]))['page_title']

.asciidoc
  = Asciidoctor.convert_file(@page[:filename], to_file: false, standalone: false, attributes: { 'skip-front-matter' => '' }).html_safe